### PR TITLE
TAD : create download link

### PR DESCRIPTION
**Pull request by akenzua**
[TP11753 ](https://maps.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNzlGODk3MENDQkM0N0FCM0ZFQzkyNEVFODEyREM0M0EifQ==&boardPopup=userstory/11753/silent)

This PR added a download link to the result heading and on click, a download of a list of all firms is initiated.

### CODE REVIEW

**Comment by davidtrussler** [comment]
This looks generally like a good piece of work 🙂  - I just have a couple of queries: 
- What is the reason for the last commit ('removed set language')? This appears to make switching between languages functional only server-side. I don't think this is a massive problem but I just wondered why it is necessary since it is a change to the existing way this works. 
- Is it possible to render a Welsh version of the the PDF? Again, I suspect this might not be a major issue since it would only be the table headings but as it stands it seems like we only are able to get an English language version.

**Comment by akenzua** [comment]
> This looks generally like a good piece of work 🙂 - I just have a couple of queries:
> 
> * What is the reason for the last commit ('removed set language')? This appears to make switching between languages functional only server-side. I don't think this is a massive problem but I just wondered why it is necessary since it is a change to the existing way this works.
> * Is it possible to render a Welsh version of the the PDF? Again, I suspect this might not be a major issue since it would only be the table headings but as it stands it seems like we only are able to get an English language version.

* The set language was producing an error, but only when you the language button more than twice (which I don't expect any real user to do, unless someone is testing the functionality plus it works anyway) and since I was thinking removing it eventually because of the lang attribute in the HTML tag. However, I have returned the function i have agreed with @andreferreiradlw to investigate the cause of the error later.
* Yeah, I have added translation to the pdf.

**Comment by davidtrussler** [comment]
> * The set language was producing an error, but only when you the language button more than twice (which I don't expect any real user to do, unless someone is testing the functionality plus it works anyway) and since I was thinking removing it eventually because of the lang attribute in the HTML tag. However, I have returned the function i have agreed with @andreferreiradlw to investigate the cause of the error later.
>> OK, sounds good to me. 

> * Yeah, I have added translation to the pdf.
>> Great - looks good!

**Review by davidtrussler — APPROVED** [review]
Noice! 👍

**Review by andreferreiradlw — APPROVED** [review]

**Pull request merged**
