### PR TITLE
TAD replace youtube video and welsh copy changes

### PR DESCRIPTION
**Pull request by akenzua**
[TP11790](https://maps.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNjA5RjRCQzM4NTlDRjBBOEQ4QzM2ODUxMEVENDhFNkUifQ==&boardPopup=userstory/11790/silent) & [TP11785](https://maps.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNjA5RjRCQzM4NTlDRjBBOEQ4QzM2ODUxMEVENDhFNkUifQ==&boardPopup=userstory/11785/silent)

This PR resolved 2 TP tickets to make up for the launch, which is 10am on Thursday. It addressed the translation copy changes for both changes, and  switched the video.

### CODE REVIEW

**Comment by ladamsatmaps19** [comment]
Would be good if the video opened in a new window but you can do that later?

**Review by ladamsatmaps19 — APPROVED** [review]

**Comment by davidtrussler** [comment]
Hi @akenzua - did the accordion click classes get added in this work? (In the comment on TP11785)

**Comment by akenzua** [comment]
> Hi @akenzua - did the accordion click classes get added in this work? (In the comment on TP11785)

No, we did not get a confirmation of what needed to be done exactly

**Comment by davidtrussler** [comment]
> No, we did not get a confirmation of what needed to be done exactly
OK, given the urgency I guess we'll need to return to that in a future ticket.

**Comment by akenzua** [comment]
> > No, we did not get a confirmation of what needed to be done exactly
> 
> OK, given the urgency I guess we'll need to return to that in a future ticket.

Definitely. Thanks

**Review by davidtrussler — COMMENTED** [review]
LGTM, although there is the outstanding task to add tracking classes to the accordion. This will need to be in a further card. 👍

**Pull request merged**
