### PR TITLE
Update Font Family

### PR DESCRIPTION
**Pull request by akenzua**
[TP12275](https://maps.tpondemand.com/restui/board.aspx?#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiOUM2MjFGQzAzOEIzQTVDNDU1NjRCMUIxQ0FENkZBOTYifQ==&boardPopup=userstory/12275/silent) 

This PR update the version on react library to 1.9.4, this version has the Roobert font used on MoneyHelper.
The Roobert font was added as part of the ticket

### CODE REVIEW

**Comment by davidtrussler** [comment]
Hi @akenzua - is there a PR for associated changes in the React Library for this piece of work?

**Comment by akenzua** [comment]
> Hi @akenzua - is there a PR for associated changes in the React Library for this piece of work?

No, there isnt.

**Comment by davidtrussler** [comment]
> > Hi @akenzua - is there a PR for associated changes in the React Library for this piece of work?
> 
> No, there isnt.

OK. We need to consider how to update the fonts for Money Helper: we can't just change the fonts on the library because we need to maintain parallel deployments for MAS and MH. So I think we need to either update the fonts only on the TAD repo or to do it on a new major version of the Library. Either way we shouldn't be pushing changes to the master branch without a review.

**Comment by akenzua** [comment]
> > > Hi @akenzua - is there a PR for associated changes in the React Library for this piece of work?
> > 
> > 
> > No, there isnt.
> 
> OK. We need to consider how to update the fonts for Money Helper: we can't just change the fonts on the library because we need to maintain parallel deployments for MAS and MH. So I think we need to either update the fonts only on the TAD repo or to do it on a new major version of the Library. Either way we shouldn't be pushing changes to the master branch without a review.

The version that has the MH font is 1.9.4 which has now been installed in this PR. TAD standalone still retains 1.9.3. I think we should maintain these in parallel, because if we keep working on TAD repo, we will soon have all the styles in the repo and that defeats the whole idea of having a library. My thoughts though.

**Comment by davidtrussler** [comment]
> > > > Hi @akenzua - is there a PR for associated changes in the React Library for this piece of work?
> > > 
> > > 
> > > No, there isnt.
> > 
> > 
> > OK. We need to consider how to update the fonts for Money Helper: we can't just change the fonts on the library because we need to maintain parallel deployments for MAS and MH. So I think we need to either update the fonts only on the TAD repo or to do it on a new major version of the Library. Either way we shouldn't be pushing changes to the master branch without a review.
> 
> The version that has the MH font is 1.9.4 which has now been installed in this PR. TAD standalone still retains 1.9.3. I think we should maintain these in parallel, because if we keep working on TAD repo, we will soon have all the styles in the repo and that defeats the whole idea of having a library. My thoughts though.

I think this needs more discussion:
- we should not use version 1.9.4 since this should be for a bug fix. If anything it should be version 2.0.0, which will allow us the scope to develop the "MAS branch" further.
- As far as I could see the version wasn't changed anyway on the library so we would be in danger of applying the new fonts on the current production version of the directory. 
- There were also some changes made to the Library beyond the fonts that were not required.

**Review by davidtrussler — APPROVED** [review]
Excellent - looks great 👍

**Pull request merged**
