### PR TITLE
TP-11816-tad-amend-single-trip-duration-filter v2

### PR DESCRIPTION
**Pull request by thenapking**
[TP-11816](https://maps.tpondemand.com/entity/11816-tad-amend-single-trip-duration-filter)

### CODE REVIEW

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/11816

**Comment by thenapking** [comment]
Added a simple change and the build passed.

**Comment by thenapking** [comment]
I reapplied all changes from the previous branch except for the update to `package_lock.json`.  Either that was it, or something unknown was up with Travis!

**Review by akenzua — APPROVED** [review]
Great work.

**Pull request merged**
